### ISSUE TITLE
Perpetual Error Pop-up when Editing *.qmd Files

### ISSUE THREAD

**Issue by murek-m** [jmbuhr/quarto-nvim-kickstarter#111]
When editing *.qmd files a persistent error message keeps popping up. The error message indicates a failure in running diagnostics with the following details:

```bash
Failed to run diagnostics: ! in callr subprocess.
Caused by error: 
! Linter 'object_length_linter' failed in test.qmd.otter.R: path[1]="test.qmd.otter.R": No such file or directory
```
<img width="947" alt="Screenshot 2024-05-03 at 23 02 01" src="https://github.com/jmbuhr/quarto-nvim-kickstarter/assets/11369435/c056df5a-bfe9-4b12-bbac-7a7f18ba77fd">

Environment:
macOS Sonoma 14.4.1 (23E224)
iTerm: v3.4.23
NVim: v0.9.5
Quarto NVim Kickstarter: v3.8.0

**Comment by jmbuhr** [comment]
See https://github.com/jmbuhr/otter.nvim/issues/116 for two solutions.

**Comment by murek-m** [comment]
Creating a ~/.lintr worked. Thanks!

**Comment by LJFRIESE** [comment]
Hey, I'm experience a similar, but possibly distinct error.

All .qmd files are receiving the following error:

{path}\{file}.qmd|1 col 1 error| Failed to run diagnostics: ! in callr subprocess. Caused by error in `loadNamespace(x)`: ! there is no package called 'lintr'

Everything else about setting up quarto seems to be working, but this is sticking. I have tried adding the .lintr file in a variety of places, from the nvim config home to the .rproj directory. I'm on Windows 10.
