### ISSUE TITLE
Does not work with nvim 0.9.5 out of the box

### ISSUE THREAD

**Issue by nichtich** [jmbuhr/quarto-nvim-kickstarter#119]
Installation from scratch with nvim 0.9.5 (the current version included in Ubuntu 24.04 LTS) gives error message

[lazydev.nvim requires Neovim >= 0.10](https://github.com/jmbuhr/quarto-nvim-kickstarter/blob/main/lua/plugins/lsp.lua#L34)

As far as I understand lazydev.nvim is not relevant for working with quarto in neovim, so it should better be disabled by default to support a straight-forward setup experience. 

More crucial seems to be [otter.nvim](https://github.com/jmbuhr/otter.nvim), it also requires Neovim >= 0.10. Any chance to get this running with nvim 0.9.5 at all?

**Comment by jmbuhr** [comment]
For time reasons I can only actively maintain the latest stable version, but feel free to take just the pieces you find interesting from my config into your own :)

For otter, yes, that would be possible, but I decided against it again for time reasons. It's actually just the vim.lsp.protocol.Methods table I use to look up up-to-date lsp request names, so that could be made available within otter itself for sub 0.10 versions. I'm open for a PR though!
