### ISSUE TITLE
Errors after running Python chunks on Linux

### ISSUE THREAD

**Issue by thadryanjs** [jmbuhr/quarto-nvim-kickstarter#27]
Thanks for working on this! It's a cool idea.

I've noticed that when I run Python chunks there seems to be some extra characters sent to the terminal, so the code executes correctly but then procudes a syntax error. I recreated the bug on an up-to-date Arch Linux system like this:

```bash
# !assuming you've backed up your config!
# changed from -r to -rf
rm -rf ~/.local/share/nvim
rm -rf ~/.local/state/nvim
```

Then get the repo:
```bach
git clone https://github.com/jmbuhr/quarto-nvim-kickstarter.git ~/.config/nvim
nvim
```

I then created a `qmd` file with the following chunks:

```{python}
print("python")
```

```{python}
print("First")
print("Second")
```

When I run the first one (using space enter), I get:

```bash
>>>print("Python")
Python
```

When I run the second one, I get the following:

```bash
>>>print("first")
first
>>>print("second")
second
>>>--
  File <stdin>, line 1
   --
    ^
SyntaxError: invalid syntax
```

It looks like an extra line that isn't Python gets submitted when I call the multi-line chunk. After some experimenting, it looks like the error does not occur when I have the cursor directly on the delimiting lines of the chunk, that is to say, when my cursor is on the:
\`\`\`\{python}

ie 

```{python}
print("First") # executing with cursor one line above gives no error, executing here does
print("Second")
```

I also noticed that sometimes the error is...
```bash
%cpaste -q
^
```
...instead of the stdin error. ...but it's not obvious to me when it is this vs the other one. I assume this is something subtle with the delineation and parsing. I might be able to take a look around the codebase at it at some point but someone more familiar might know where to look right away.

If you could point me in the right direction that would be awesome. 

Thanks again.

**Comment by jmbuhr** [comment]
When this variable is set to `1` (the default), the configuration assumes that a python terminal is an ipython terminal:
https://github.com/jmbuhr/quarto-nvim-kickstarter/blob/5281051ded85a9dc41d72cd31af30a0cd9639216/lua/plugins/quarto.lua#L539
And then uses the special magic ipython paste command here: https://github.com/jmbuhr/quarto-nvim-kickstarter/blob/5281051ded85a9dc41d72cd31af30a0cd9639216/lua/plugins/quarto.lua#L519
(because ipython has a problem with multiline chunks otherwise)

You can either disable this by setting it to 0 or deleting the line, or use ipython (`<space>ci` instead of `<space>cp`).
