### ISSUE TITLE
Failed to run `config` for nvim-lspconfig

### ISSUE THREAD

**Issue by hopezh** [jmbuhr/quarto-nvim-kickstarter#36]
I got the following error message after installing the quarto-nvim-kickstarter:

```
Failed to run `config` for nvim-lspconfig

C:/Users/[USER]/AppData/Local/nvim/lua/plugins/quarto.lua:303: attempt to concatenate local 'resource_path' (a nil value)

# stacktrace:
  - lua/plugins/quarto.lua:303 _in_ **config**
  - quarto-nvim\lua\quarto\init.lua:3
  - quarto-nvim\plugin\quarto.lua:16
  - vim\_editor.lua:341 _in_ **cmd**
  - lua/config/lazy.lua:17
  - init.lua:2
```

I'm using:
Windows 11
PowerShell
Neovim: v0.10.0-dev-400+ge41b2e34b

**Comment by jmbuhr** [comment]
Loks like this line https://github.com/jmbuhr/quarto-nvim-kickstarter/blob/1b322185614b0a43775df2859e1822e6fd585993/lua/plugins/quarto.lua#L302 fails because it can't get the location of quarto resources (to help with lua autocompletion when writing quarto filters). Which version of quarto do you have installed?

Regardless, I will add a nil check there and warn of quarto is not installed.
