### ISSUE TITLE
Error with `telescope.nvim`

### ISSUE THREAD

**Issue by danielw2904** [jmbuhr/quarto-nvim-kickstarter#5]
I am getting the following error after cloning on windows 11. I'm pretty new to nvim but it seems `telescope-fzf-native` is missing and I cannot seem to be able to figure out how to install it (Mason does not show it). I would be grateful for any suggestions!

```

Failed to run `config` for telescope.nvim

...a/lazy/telescope.nvim/lua/telescope/_extensions/init.lua:10: 'fzf' extension doesn't exist or isn't installed: ...nvim-data/lazy/telescope-fzf-native.nvim/lua/fzf_lib.lua:11: cannot load module 'C:/Users/danie/AppData/Local/nvim-data/lazy/telescope-fzf-native.nvim/lua/../build/libfzf.dll': The specified module could not be found.^M


# stacktrace:
  - telescope.nvim\lua\telescope\_extensions\init.lua:10 _in_ **load_extension**
  - telescope.nvim\lua\telescope\_extensions\init.lua:62 _in_ **load_extension**
  - ui.lua:53 _in_ **config**
  - ~\AppData\Local\nvim/lua/config/lazy.lua:17
```

**Comment by jmbuhr** [comment]
`fzf` is a fuzzy finder that speeds up telescope search, and the fzf-native extension tries to automatically install that. But in order to do so it needs the dependencies to build fzf, which don't come with windows: https://github.com/nvim-telescope/telescope-fzf-native.nvim#make-linux-macos-windows-with-mingw

You can either install them and then [this line](https://github.com/jmbuhr/quarto-nvim-kickstarter/blob/9a11e943f4338b96d15e9e3a4706c71faf896e3e/lua/plugins/ui.lua#L60) will automatically build fzf or comment out the line and not use fzf.

**Comment by danielw2904** [comment]
Thank you very much for the quick answer. It seems my misunderstanding was with windows (possibly the PATH) since I had MinGW installed but it somehow couldn't find make. I installed make using `choco` for future reference.
