### ISSUE TITLE
Tab completed on quoted variable names duplicates initial typing

### ISSUE THREAD

**Issue by py9mrg** [jmbuhr/quarto-nvim-kickstarter#78]
Hello (again, sorry!),

I don't think this is necessarily the right repos to post this issue but I'm not sure whether this should go to the mason/r-languageserver, treesitter, nvim-cmp, or here. (I don't have the problem with vscode so I don't think this is a languageserver issue).

Let's say I start typing a mutate and I'm beginning to type the variable name "variable_one":

```r
data |>
  mutate(
    variab
  )
```

when the variable name is sensible (i.e. snakecase) then there is no problem, when I hit tab the name is completed to `variable_one` perfectly. The issue comes when dealing with bad variable names (i.e. ones that have to be backquoted like `Variable One`). If I start typing like:

```r
data |>
  mutate(
    `Variab
  )
```

Then the correct `Variable One` is suggested, but when I hit tab I get:

```r
data |>
  mutate(
    `Variab `Variable One`
  )
```

So I *think* treesitter is working properly in the sense that it's suggesting correctly - but whatever plugin is doing the tab completion (nvim-cmp?) is getting confised by the initial backtick.

Assuming this isn't an issue with the kickstarter, would you mind pointing me in the right direction of the repos to post an issue on please?

**Comment by jmbuhr** [comment]
Interesting, might be an interaction between plugins or just an issue with the completion source. Which nvim-cmp source gives you the variable names? maybe the buffer source?

Because the R language server itself only gives us static analysis, it can not give us completions for dynamically defined things inside of objects such as columnames.

**Comment by py9mrg** [comment]
Happy new year. I'm not sure to be honest, I'm pretty new to nvim - thought I'd give it a whirl over Christmas - which is why I'm using this kickstarter (I'd be totally lost without it - so thanks!). The only thing I changed is to set the copilot to disabled but otherwise it's a completely fresh install. So I guess I'm using whatever nvim-cmp source is the default? But I have tried on Windows, WSL, and Linux and the same issue on all so I don't think it's a quirk of my specific system. It's not that big an issue really though.

**Comment by jmbuhr** [comment]
There is no "default" nvim-cmp source. It's just a completion plugin for which other people can write sources such as for paths, words in the current buffer, language server completions etc.

Also see https://github.com/jmbuhr/quarto-nvim-kickstarter/issues/57

See for example, how we don't get a completion for the column names (backticks or no backticks) here: 
![image](https://github.com/jmbuhr/quarto-nvim-kickstarter/assets/17450586/983b73c9-115e-4c83-be70-f6d87bc3df6f)

because the language server does not execute our R code, which if would have to do to know the column names.
 
For regular variables I am also unable to reproduce your issue:
![image](https://github.com/jmbuhr/quarto-nvim-kickstarter/assets/17450586/585d5f99-06f7-47e8-af30-6aa890507105)

![image](https://github.com/jmbuhr/quarto-nvim-kickstarter/assets/17450586/e12020bc-d5b5-4885-a64f-e7957a8809b9)

Do you have a document that leads to this behavior?

**Comment by py9mrg** [comment]
Oh I should have said, sorry, I was talking about .r not .qmd files. Although iirc I checked both and had the issue.

I've dug into this a bit more and it seems a really niche problem. There's *something* about the number of characters are the start of the variable name combined with the number of spaces in the variable name:

```r
library(dplyr)


# works fine
df <- tibble(
  variable_one = 1:10,
  `variable one two` = 1:10
)

df |>
  mutate(
    variable_one = 1:10,
    `variable one two` = 1:10
  )


# doesn't work

new_df <- tibble(
  `va riable one` = 1:10
)

new_df |>
  mutate(
    `va `va riable one`
  )
```

In the above code, if I type "`va riab" then I get the suggestion but when I hit enter on it, it completes as above. I haven't managed to narrow it down to a specific scenario yet.

Even more weird is, if I ignore the spaces when typing out the variable names it suggests and autocompletes fine:

![image](https://github.com/jmbuhr/quarto-nvim-kickstarter/assets/12600721/74a7df81-e72d-419c-a7b5-eef88c133510)

![image](https://github.com/jmbuhr/quarto-nvim-kickstarter/assets/12600721/30f0b803-02e6-4dec-8310-79c8498fc0ce)

I'm tempted to close this issue tbh - the fix is just to type names ignoring spaces.

**Comment by jmbuhr** [comment]
I see, I'm expecting nvim-cmp to complete words, so the `va ` before `riable is not part of the word being completed, hence it can't be replaced by the completed word. In a way, you are running into this issue because nvim-cmp is cleverly fuzzy matching such that even though it only has `ria` it also finds completions where this is in the middle (could even be with characters left out). Other editors or plugin may not use fuzzy matching, so you wouldn't even get any completion there.
