### ISSUE TITLE
can't get bibliography to autocomplete

### ISSUE THREAD

**Issue by larkinrt** [jmbuhr/quarto-nvim-kickstarter#81]
Hi, thank you for this it's super helpful. For some reason I can't get my bilbliography data to autocomplete. It is set up properly in the qmd document and compiles fine when I run quarto preview, but doesn't appear as an autocomplete. Am I missing a place to put the references file outside of the qmd doc? I am coming from doom-emacs using citar where that is indicated in the settings.

Also, "right" is misspelled using SPC-s-r, not sure if that was intentional.

**Comment by jmbuhr** [comment]
Can you provide a reproducible example?

**Comment by larkinrt** [comment]
Ok I figured it out, if I use an absolute path in the YAML data then it will work, but if I use a relative path it doesn't. I do not know why.

I am on macOS using nvim from homebrew. Maybe this is a macOS specific bug?

**Comment by larkinrt** [comment]
Ok now I really figured it out.

Adding the following to my init.lua resolved the issue. The problem was the working directory wasn't being set when files were opened, so the relative path of the .bib couldn't function (nvim was looking from the perspective of root).

```
vim.cmd('set autochdir')
```

I'm not sure if you have this enabled in your own config, but for anybody coming from the kickstarter vids without a background in vim this might be helpful to mention somewhere.

**Comment by jmbuhr** [comment]
Thanks for the troubleshooting! I'll also see if the plugin can be more robust against this.

**Comment by dmnkf** [comment]
I am currently troubleshooting the same problem.

Your kickstart definitely works as intended as if I setup a 2nd nvim instance using your config it works out of the box.

However I am not quite getting to how you configured the lsp that the references work. Is there anything else that is responsible for retrieving the references/yaml highlighting? (I assume the issue is related and my setup is missing something).

<img width="868" alt="Screenshot 2024-08-12 at 09 58 01" src="https://github.com/user-attachments/assets/ad993aca-1a7c-40fe-b198-9d709b897333">

<img width="847" alt="Screenshot 2024-08-12 at 09 58 24" src="https://github.com/user-attachments/assets/338ebc4b-f089-4ab7-a0c0-7e8fb4b962a6">

I copied all the lsp related stuff almost 1:1, but I am not getting the same auto complete and the yaml is also not formatted nicely like with yours. 

<img width="546" alt="Screenshot 2024-08-12 at 09 59 27" src="https://github.com/user-attachments/assets/8e96d0f0-c01e-496f-8880-1eb39b709986">

I am not quite sure what else to do.

**Comment by jmbuhr** [comment]
For reference completion you need https://github.com/jmbuhr/cmp-pandoc-references/

**Comment by jmbuhr** [comment]
For the yaml I assume you just have to install the treesitter grammar with `:TSInstall yaml` and reload.

**Comment by dmnkf** [comment]
Wow I am blind. I forgot to extend my cmp sources... 

Thank you so much
